language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -U pytest
  - pip install -r requirements.txt
  - pip install .

script:
  - pytest coolbox --doctest-modules
  - pytest tests