name: Python Package using Conda

on: [push, pull_request]


jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install libcurl4-openssl-dev
        $CONDA/bin/conda env update --name base --file environment.yml
        $CONDA/bin/pip install .
    - name: Test with pytest
      run: |
        export PATH=$CONDA/bin:$PATH
        $CONDA/bin/conda install --yes pytest
        $CONDA/bin/conda install -c conda-forge --yes pytest-tornasync
        cd tests
        $CONDA/bin/pytest
