name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --name base --file environment.yml
    - name: Test with pytest
      run: |
        echo at $(pwd)
        $CONDA/bin/conda install --yes pytest
        $CONDA/bin/pytest
