name: 'Trigger-Binder-build'
on:
  push:
    branches:
      - master

jobs:
  trigger-binder-build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1
        with:
          target-repo: GangCaoLab/CoolBox
          service-name: github
          target-state: master
          use-default-build-servers: true
          debug: true
